---
- include_vars: ../../../personal.yml

- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create mysql database
  mysql_db: 
    name: "{{ wordpress_db }}"
    state: present
  become: yes

- name: Create mysql user
  become: yes
  mysql_user: 
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
