---
- name: Add php5.6 repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Run apt update
  apt:
    update_cache: yes

- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - php5.6-mysql
    - php5.6
    - libapache2-mod-php5.6
    - php5.6-mcrypt
